name: Publish snapshot package
on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  publish-snapshots:
    environment:
      name: prod
      url: ${{ steps.publish.outputs.url }}
    name: Publish snapshot packages
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm i
          npm test
      - id: publish
        run: |
          version=$(jq -r .version package.json)-snapshot$PR_NUMBER.$RUN_NUMBER.$RUN_ATTEMPT
          npm version $version --no-git-tag-version
          npm run build
          cd dist
          npm publish --provenance --access public --tag snapshot
          echo "url=https://www.npmjs.com/package/@waves/ts-lib-crypto/v/$version" >> "$GITHUB_OUTPUT"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
